import { Link } from "react-router-dom";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter, Separator } from "@jofrom/design-system/ui";
import { PageHeader } from "@/components/primitives";
import { StatusBadge } from "@/components/StatusBadge";
import { deptLabel } from "@/lib/prototype-data";
import { useCommons } from "@/lib/use-commons";

export function RecentPage() {
  const { recent } = useCommons();
  return (
    <>
      <PageHeader
        title="Recent outputs"
        description="Compiler Records — the finished work Jo from has produced across your company. Newest first."
      />
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
        {recent.map((o) => (
          <Card key={o.id} className="gap-3">
            <CardHeader>
              <CardTitle className="text-base">{o.title}</CardTitle>
              <CardDescription>{o.type} · {deptLabel(o.department)}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-2 text-sm">
              <p className="text-foreground">{o.summary}</p>
              <div className="flex justify-between text-xs"><span className="text-muted-foreground">Generated by</span><span className="font-medium">{o.generatedBy}</span></div>
              <div className="flex justify-between text-xs"><span className="text-muted-foreground">When</span><span className="font-medium">{o.timestamp}</span></div>
              <Separator />
              <div className="flex flex-wrap items-center gap-1 text-xs">
                {o.history.map((h, i) => (
                  <span key={i} className="flex items-center gap-1">
                    {i > 0 && <span className="text-muted-foreground/40">→</span>}
                    <span className="rounded bg-accent px-1.5 py-0.5">{h}</span>
                  </span>
                ))}
              </div>
            </CardContent>
            <CardFooter className="justify-between">
              <StatusBadge kind={o.statusKind} label={o.statusLabel} />
              {o.sourceObjectId && (
                <Link to={`/objects/detail/${o.sourceObjectId}`} className="text-sm font-medium text-primary hover:underline">
                  Open object →
                </Link>
              )}
            </CardFooter>
          </Card>
        ))}
      </div>
    </>
  );
}
